services:
  - type: web
    name: medgpt-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: OPENAI_API_KEY
        value: sk-... # Replace with your actual OpenAI API key on Render 